"""
Cirrhosis AI Diagnosis - Interpretable Stacked Ensemble API

This is the main FastAPI application for the Cirrhosis AI Diagnosis system.
It provides endpoints for:
- Training the stacked ensemble model
- Making predictions with interpretable explanations
- Generating LLM-powered clinical narratives
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from backend.routers import prediction_router, training_router


# Create FastAPI app
app = FastAPI(
    title="Cirrhosis AI Diagnosis API",
    description="""
    ## Interpretable Stacked Ensemble for Cirrhosis Patient Status Prediction
    
    This API provides:
    - **Accurate Predictions** using XGBoost, LightGBM, CatBoost ensemble
    - **Interpretable Explanations** via shallow Decision Tree rules
    - **Clinical Narratives** generated by LLM grounded in model logic
    
    ### Model Architecture
    
    **Layer 1 - Base Models:**
    - XGBoost Classifier (Performance)
    - LightGBM Classifier (Performance)
    - CatBoost Classifier (Performance)
    - Decision Tree Classifier (Interpreter, max_depth=4)
    
    **Layer 2 - Meta-Model:**
    - Logistic Regression
    
    ### Target Variable
    - **C**: Censored (patient alive at end of study)
    - **CL**: Censored due to liver transplant
    - **D**: Death
    """,
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)

# CORS middleware for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure appropriately for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routers
app.include_router(prediction_router)
app.include_router(training_router)


@app.get("/", tags=["Health"])
async def root():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "service": "Cirrhosis AI Diagnosis API",
        "version": "1.0.0"
    }


@app.get("/health", tags=["Health"])
async def health_check():
    """Detailed health check."""
    return {
        "status": "healthy",
        "components": {
            "api": "running",
            "model": "check /train/status for model status"
        }
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)